In [2]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
import pandas as pd

2024-01-18 17:11:09.823492: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-01-18 17:11:10.060700: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-18 17:11:10.060747: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-18 17:11:10.090437: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-18 17:11:10.154315: I tensorflow/core/platform/cpu_feature_guar

In [3]:
df = pd.read_excel("VIC-20240113-2028.xls")
data_df = df['output'].to_numpy()
target = np.array([[i] for i in data_df])
data = np.array([[i] for i in data_df])

data = data[:-1]
target = target[1:]

In [40]:
n = (data - 1).size
size_train = int(n * 0.95)
size_val = n - 1 - size_train

x_train, x_val, x_test = data[:size_train], data[size_train:size_train + size_val], data[size_train + size_val:]

y_train, y_val, y_test = target[:size_train], target[size_train:size_train + size_val], target[size_train + size_val:]

n, size_train, size_val, n - size_train - size_val

(249, 236, 12, 1)

In [41]:
x_train = np.reshape(x_train, (x_train.shape[0], 1, x_train.shape[1]))
x_test = np.reshape(x_test, (x_test.shape[0], 1, x_test.shape[1]))

In [42]:
model = Sequential()
model.add(LSTM(units=1000, activation='relu', input_shape=(1, 1)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [43]:
model.fit(x_train, y_train, epochs=150, validation_data=(x_val, y_val))

Epoch 1/150
8/8 [==============================] - 2s 66ms/step - loss: 2538743040.0000 - val_loss: 2799897600.0000
Epoch 2/150
8/8 [==============================] - 0s 39ms/step - loss: 2232112896.0000 - val_loss: 2443968256.0000
Epoch 3/150
8/8 [==============================] - 0s 41ms/step - loss: 1934572160.0000 - val_loss: 2087817856.0000
Epoch 4/150
8/8 [==============================] - 0s 43ms/step - loss: 1628806784.0000 - val_loss: 1715018368.0000
Epoch 5/150
8/8 [==============================] - 0s 41ms/step - loss: 1310206208.0000 - val_loss: 1328844544.0000
Epoch 6/150
8/8 [==============================] - 0s 42ms/step - loss: 986356096.0000 - val_loss: 949104640.0000
Epoch 7/150
8/8 [==============================] - 0s 42ms/step - loss: 678032000.0000 - val_loss: 604555712.0000
Epoch 8/150
8/8 [==============================] - 0s 43ms/step - loss: 410266272.0000 - val_loss: 329370624.0000
Epoch 9/150
8/8 [==============================] - 0s 44ms/step - loss: 207392

In [44]:
predictions = model.predict(x_test)

predictions

1/1 [==============================] - 0s 300ms/step


array([[54886.18]], dtype=float32)

In [45]:
y_test

array([[55000]])

array([[113.8203125]])